[tool.poetry]
name = "ghostcoder"
version = "0.0.12"
description = ""
authors = ["Albert Örwall <albert@a20g.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
openai = "^1.2.3"
langchain = "^0.0.334"
pydantic = "^1"
pytest = "^7.3.1"
tiktoken = "^0.5.1"
pathspec = "^0.11.1"
gitpython = "^3.1.31"
pyfakefs = "^5.2.3"
tree-sitter-languages = "^1.7.0"
ipython = "^8.16.1"
llama-index = "^0.8.68"
streamlit = "^1.28.1"

[tool.poetry.group.dev.dependencies]
ipywidgets = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
